### ISSUE TITLE
Nit: follow repository naming convention

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-string-replaceall#1]
Repositories tend to have names of the form "proposal-string-replace-all". This isn't documented anywhere, though we can document it soon.

**Comment by psmarshall** [comment]
I did see this part: https://github.com/tc39/proposals#onboarding-existing-proposals

Which seems to indicate the name will be changed if/when it goes to stage 1 and is transferred to the TC39 org, so I guess we can leave it until then, so that we don't end up with 3 links instead of 2. WDYT?

**Comment by littledan** [comment]
Sounds fine to me, though GitHub does insert redirects for you (for the repository at least, not gh-pages).
