### ISSUE TITLE
Also specifying a function as a second parameter similar to "replace"

### ISSUE THREAD

**Issue by MaxGraey** [tc39/proposal-string-replaceall#11]
Details: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_function_as_a_parameter

**Comment by mathiasbynens** [comment]
Yep, TC39 already decided in November 2017 this is the way forward. https://tc39.github.io/tc39-notes/2017-11_nov-28.html#10ih-stringprototypereplaceall-for-stage-1
