### ISSUE TITLE
Alternative: `all` parameter for replace

### ISSUE THREAD

**Issue by jsejcksn** [tc39/proposal-string-replaceall#23]
I noticed [in the README](https://github.com/tc39/proposal-string-replaceall/tree/f709fbfe8ff3f62d7627c7e9ce54ba95b4efcd53#what-about-adding-a-limit-parameter-to-replace-instead) it says:

> **What about adding a `limit` parameter to `replace` instead?**
>
> A: This is an awkward interface — because the default limit is 1, the user would have to know how many occurrences already exist, or use something like Infinity.

But this would not be an issue if the parameter were simply `all` instead of `limit` and could be set to `true` to provide the functionality of this proposal.

**Comment by mathiasbynens** [comment]
It's still a more convoluted/awkward interface than a first-class new method. Given how common the use case of wanting to replace all occurrences of a string is, the committee has already agreed that a separate method is the way to go.
