### ISSUE TITLE
Missed matchAll-related features

### ISSUE THREAD

**Issue by zloirock** [tc39/proposal-string-replaceall#25]
#24 adds changes to `String#matchAll`, but not to related methods. Maybe, in this case, makes sense remove handling non-global regexes from `RegExp.prototype[@@matchAll]`, `CreateRegExpStringIterator`, `%RegExpStringIteratorPrototype%.next()` and simplify those methods?

**Comment by ljharb** [comment]
I don’t think that’s necessary or ideal. The string matchAll method, alone, is where the confusion lies with non-global regexes.
