### ISSUE TITLE
It can break the web

### ISSUE THREAD

**Issue by zloirock** [tc39/proposal-string-replaceall#5]
[`SugarJS`](https://sugarjs.com/docs/#/String/replaceAll) provides a method with the same name, but with another signature. Related https://github.com/tc39/proposal-flatMap/pull/56

**Comment by mathiasbynens** [comment]
Thanks for the pointer! As with all proposals that extend built-ins, it's possible that this one turns out to be non-web-compatible. There's really only one way to find out, though! Closing this issue for now as there's nothing actionable.
